const List posts = [
  {
    "id": 1,
    "name": "stmarksbasilica",
    "profileImg": "./assets/images/stmarksbasilica.jpg",
    "postImg": "./assets/images/stmarksbasilica.jpg",
    "caption": "St. Marksbasilica cherch",
    "isLoved": true,
    "commentCount": "777",
    "likedBy": "santorini",
    "timeAgo": "1 day ago",
  },
  {
    "id": 2,
    "name": "santorini",
    "profileImg": "./assets/images/santorini.jpg",
    "postImg": "./assets/images/santorini.jpg",
    "caption": "Santorini Greece",
    "isLoved": true,
    "commentCount": "117",
    "likedBy": "paris",
    "timeAgo": "1 day ago",
  },
  {
    "id": 3,
    "name": "paris",
    "profileImg": "./assets/images/paris.jpg",
    "postImg": "./assets/images/paris.jpg",
    "caption": "Paris city night view",
    "isLoved": false,
    "commentCount": "93",
    "likedBy": "saopaulo",
    "timeAgo": "1 day ago",
  },
  {
    "id": 4,
    "name": "saopaulo",
    "profileImg": "./assets/images/saopaulo.jpg",
    "postImg": "./assets/images/saopaulo.jpg",
    "caption": "Saopaulo city",
    "isLoved": true,
    "commentCount": "30",
    "likedBy": "paris",
    "timeAgo": "1 day ago",
  },
  {
    "id": 5,
    "name": "murano",
    "profileImg": "./assets/images/murano.jpg",
    "postImg": "./assets/images/murano.jpg",
    "caption": "Murano",
    "isLoved": false,
    "commentCount": "10",
    "likedBy": "gondola",
    "timeAgo": "1 day ago",
  },
  {
    "id": 6,
    "name": "gondola",
    "profileImg": "./assets/images/gondola.jpg",
    "postImg": "./assets/images/gondola.jpg",
    "caption": "Gondola",
    "isLoved": true,
    "commentCount": "30",
    "likedBy": "venice",
    "timeAgo": "1 day ago",
  },
  {
    "id": 7,
    "name": "venice",
    "profileImg": "./assets/images/venice.jpg",
    "postImg": "./assets/images/venice.jpg",
    "caption": "venice city",
    "isLoved": true,
    "commentCount": "30",
    "likedBy": "murano",
    "timeAgo": "1 day ago",
  },
];
